







	



.build/uno/Adafruit_GFX/Adafruit_GFX.d : lib/Adafruit_GFX/Adafruit_GFX.cpp
	@mkdir -p .build/uno/Adafruit_GFX
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/Adafruit_GFX -Ilib/Adafruit_NeoPixel -Ilib/Adafruit_NeoMatrix -Ilib/Adafruit_NeoMatrix/extras -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/CapacitiveSensor -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/uno/Adafruit_GFX/Adafruit_GFX.d .build/uno/Adafruit_GFX/" | cat - $@ > $@~ && mv $@~ $@

.build/uno/Adafruit_GFX/glcdfont.d : lib/Adafruit_GFX/glcdfont.c
	@mkdir -p .build/uno/Adafruit_GFX
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/Adafruit_GFX -Ilib/Adafruit_NeoPixel -Ilib/Adafruit_NeoMatrix -Ilib/Adafruit_NeoMatrix/extras -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/CapacitiveSensor -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/uno/Adafruit_GFX/glcdfont.d .build/uno/Adafruit_GFX/" | cat - $@ > $@~ && mv $@~ $@



.build/uno/Adafruit_GFX/dependencies.d : .build/uno/Adafruit_GFX/Adafruit_GFX.d .build/uno/Adafruit_GFX/glcdfont.d
	@echo [96mScanning dependencies of Adafruit_GFX[0m
	@mkdir -p .build/uno/Adafruit_GFX
	@cat $^ > $@;

all : .build/uno/Adafruit_GFX/dependencies.d
	@true

